# Generated by Django 4.1.13 on 2024-01-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itinerary_qr_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='qr_code_id',
        ),
    ]
