# Generated by Django 4.1.13 on 2024-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_itinerary_qr_id_itinerary_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='qr_url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
